server:
  port: 6001
spring:
  application:
    name: star-springboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dong.springcloud.entity
logging:
  level:
    com.dong.springcloud: debug

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false #开启优化，如果开启优化，在分页页码结果没有数据的时候,会查询最后一页数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true