server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务路由
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
            - After=2020-10-10T08:01:51.171+08:00[Asia/Shanghai]
#            - Before=2020-10-10T08:11:51.171+08:00[Asia/Shanghai]
#            - Between=2020-10-10T08:11:51.171+08:00[Asia/Shanghai],2020-10-10T08:11:51.171+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org  #curl http://localhost:9527/payment/get/1 -H "Host:www.anotherhost.org"
#            - Query=green   #curl http://localhost:9527/payment/get/1?green=11 -H "Host:www.anotherhost.org"
            - Method=GET
#            curl http://localhost:9527/payment/get/1 --cookie "username=zzyy" -H "X-Request-Id:123"

#          filters:
#            - AddRequestHeader=X-Request-red, blue
#            - AddRequestParameter=X-Request-Id, 1024

        - id: payment_routh2 #payment_route #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#          filters:
#            - StripPrefix=1

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
